[package]
name = "predicated_ordered"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
pin-utils = "0.1.0-alpha.4"
hashbrown = { version = "0.6.3", optional = true }

[features]
no_std = ["hashbrown"]

